# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WAVE_ROVER_UI(object):
    def setupUi(self, WAVE_ROVER_UI):
        WAVE_ROVER_UI.setObjectName("WAVE_ROVER_UI")
        WAVE_ROVER_UI.resize(807, 531)
        self.centralwidget = QtWidgets.QWidget(WAVE_ROVER_UI)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 481, 391))
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 250, 61, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 330, 61, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(710, 330, 61, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(630, 410, 61, 61))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(630, 330, 61, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 430, 71, 41))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(520, 20, 271, 181))
        self.textEdit.setObjectName("textEdit")
        WAVE_ROVER_UI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WAVE_ROVER_UI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 22))
        self.menubar.setObjectName("menubar")
        WAVE_ROVER_UI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WAVE_ROVER_UI)
        self.statusbar.setObjectName("statusbar")
        WAVE_ROVER_UI.setStatusBar(self.statusbar)

        self.retranslateUi(WAVE_ROVER_UI)
        QtCore.QMetaObject.connectSlotsByName(WAVE_ROVER_UI)

    def retranslateUi(self, WAVE_ROVER_UI):
        _translate = QtCore.QCoreApplication.translate
        WAVE_ROVER_UI.setWindowTitle(_translate("WAVE_ROVER_UI", "MainWindow"))
        self.pushButton.setText(_translate("WAVE_ROVER_UI", "UP"))
        self.pushButton_2.setText(_translate("WAVE_ROVER_UI", "LEFT"))
        self.pushButton_3.setText(_translate("WAVE_ROVER_UI", "RIGHT"))
        self.pushButton_4.setText(_translate("WAVE_ROVER_UI", "DOWN"))
        self.pushButton_5.setText(_translate("WAVE_ROVER_UI", "STOP"))
        self.label.setText(_translate("WAVE_ROVER_UI", "Polar Noise"))
